### PR TITLE
url-strings: Test and Documentation Changes

### PR DESCRIPTION
**Pull request by tim-brown**
T&D for url-strings-branch which separates URL parsing from
url network actions.

### CODE REVIEW

**Comment by jeapostrophe** [comment]
Can you combine the two pull requests?

**Comment by tim-brown** [comment]
Can I? One is on racket/net and one is on racket. So I didn't expect to be able to just make a single pull request on the two repositories.

I'm also still "all thumbs" with git/github, so guidance would be appreciated if you want me to merge the pull requests.

Tim

If I'm wrong, would appreciate a quick 

On 30 May 2015 18:11:30 BST, Jay McCarthy notifications@github.com wrote:

> Can you combine the two pull requests?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/racket/net/pull/4#issuecomment-107066921

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeapostrophe** [comment]
Oh duh. Ya you're right. Once the other one is ready, we'll merge both

**Comment by tim-brown** [comment]
Just to be clear... You guys have both sets of changes which you're preparing... You're not waiting for me to submit anything else. That is the case?

On 30 May 2015 18:35:29 BST, Jay McCarthy notifications@github.com wrote:

> Oh duh. Ya you're right. Once the other one is ready, we'll merge both
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/racket/net/pull/4#issuecomment-107069987

## 

## Sent from my Android device with K-9 Mail. Please excuse my brevity.

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tim-brown** [comment]
Just to be clear... You guys have both sets of changes which you're preparing... You're not waiting for me to submit anything else. That is the case?

On 30 May 2015 18:35:29 BST, Jay McCarthy notifications@github.com wrote:

> Oh duh. Ya you're right. Once the other one is ready, we'll merge both
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/racket/net/pull/4#issuecomment-107069987

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stamourv** [comment]
Merged

**Pull request closed without merging**
