### PR TITLE
add note about obsolete list of MIME subtypes

### PR DESCRIPTION
**Pull request by jbclements**
This doc note would have saved me some time....

### CODE REVIEW

**Comment by samth** [comment]
Why not just fix the list to be up to date?

**Comment by jbclements** [comment]
> On Mar 24, 2016, at 11:44 AM, Sam Tobin-Hochstadt notifications@github.com wrote:
> 
> Why not just fix the list to be up to date?

That was my original plan. However, in the source for mime.rkt, there’s an explicit note to the effect that we don’t keep these up to date. Furthermore, the actual list is … very long. Thousands of entries? Take a look yourself:

http://www.iana.org/assignments/media-types/media-types.xhtml

John

**Comment by samth** [comment]
If we're not keeping up to date, then why have anything in the docs at all? An out-of-date list with a note is only marginally better than one without the note -- better to ditch the list entirely.

**Comment by jbclements** [comment]
> On Mar 24, 2016, at 3:32 PM, Sam Tobin-Hochstadt notifications@github.com wrote:
> 
> If we're not keeping up to date, then why have anything in the docs at all? An out-of-date list with a note is only marginally better than one without the note -- better to ditch the list entirely.

I don’t feel strongly about it, but I think that having the older list there is helpful in the same way that example code is. It helps people to understand the space of possibilities.

John

**Comment by samth** [comment]
If we're going for examples, we should make it much shorter so it doesn't feel like it might be exhaustive.

Also, what does "any subtype is allowed as a downcased version of the specification from the header." mean? Does that mean that anything is allowed?

**Comment by jbclements** [comment]
> On Mar 24, 2016, at 3:36 PM, Sam Tobin-Hochstadt notifications@github.com wrote:
> 
> If we're going for examples, we should make it much shorter so it doesn't feel like it might be exhaustive.
> 
> Also, what does "any subtype is allowed as a downcased version of the specification from the header." mean? Does that mean that anything is allowed?

No clue. I didn’t read that part of the docs carefully. I agree that it’s confusing and should be rewritten, though :).

John

**Comment by samth** [comment]
Committed as https://github.com/racket/racket/commit/762994654ceebf1fe14747a7311fbce15997d162 in the racket/racket repository.

**Pull request closed without merging**
