### PR TITLE
Add new RFC6265-compliant cookies/ folder, modules, tests, docs.

### PR DESCRIPTION
**Pull request by RenaissanceBug**
- Add new modules, docs, and tests in cookies/
  - Server: parse Cookie header, make cookies, make Set-Cookie header
  - User agent:
    - parse Set-Cookie header
    - save cookies
    - make Cookie header
    - interface for substituting better cookie storage
  - Common functionality: validate cookie parts
- Add deprecation notice to old cookie lib

### CODE REVIEW

**Comment by jeapostrophe** [comment]
This looks really great. My preference, however, is to patch this collection to say the code is deprecated and suggest that users install the net-cookies package and have everything else in another package you put on the pkg server. My taste is that the net package is too large. If you (or someone else) greatly disagrees, I am not stuck on this opinion, however.

**Comment by RenaissanceBug** [comment]
Fine by me.

I can see it'll take me some time to figure out how to repackage it. Would you say it's appropriate to make this library an extension to the net collection? And if so, is there another package that it would make sense to model this package's structure on? (Just from looking at the package system docs, it's not immediately clear how I'll want to structure the dir tree for such a package.)

**Comment by jeapostrophe** [comment]
It might look something like this package:

https://github.com/racket/data/tree/master/data-enumerate-lib

The collection in the info file would be 'multi and the directory structure would be net/cookies/\* with main.rkt as the main file and then things coming off that.

**Comment by RenaissanceBug** [comment]
OK. It's up on the package server as net-cookies, and on GH at https://github.com/RenaissanceBug/racket-cookies now. Thanks.

**Comment by jeapostrophe** [comment]
Okay. I just installed it and checked it out. It all looks well. Can you revise the push to just have the net/cookie doc updates?

**Comment by RenaissanceBug** [comment]
Done. Let me know if anything else is needed.

**Comment by jeapostrophe** [comment]
This is awesome. Thanks so much!

**Comment by RenaissanceBug** [comment]
Sorry, just noticed that before I made the last edit, I'd also put in a change to the deprecation notice for the cookie unit, and that's causing an erroneous dependency on my package. I'll fix that and submit a PR in the next few minutes.

**Pull request merged**
